name: "Green Pipeline Run View"
description: |
    The Green Pipeline allows a user to run joint_ere, enie, or both; merge the data if both are used; and generate visualization of the individual and merged output.
data-object: com.artistech.ee.beans.Data
parts:
    input:
        requires: []
        page: pipeline.jsp
        output-dir: input
        parameters:
            - parameter:
                name: SGM_File
                value: ""
                type: file
    joint_ere:
        output-dir: joint_ere_out
        requires:
            - input
        page: JointEre
        parameters:
            - parameter:
                name: model
                value: models/joint/joint_model
                values:
                    - models/joint/joint_model
                type: select
    enie:
        output-dir: enie_out
        requires:
            - input
        page: ENIE
        parameters:
            - parameter:
                name: property
                value: props/enie.property
                values:
                    - props/enie.property
                type: select
    merge:
        output-dir: merge_out
        requires:
            - input
            - joint_ere
            - enie
        page: Merge
        parameters: []
    visualize:
        output-dir: viz_out
        requires:
            - input
        page: Visualize
        parameters: []
        multi-run: true
