name: "Green Pipeline Run View"
parts:
    input:
        requires: []
        page: pipeline.jsp
        parameters: []
    joint_ere:
        requires:
            - input
        page: joint_ere.jsp
        parameters:
            - parameter:
                name: dummy1
                value: dummy1Value1
                values: [dummy1Value1, dummy1Value2, dummy1Value3]
            - parameter:
                name: dummy2
                value: dummy2Value1
                values: [dummy2Value1, dummy2Value2, dummy2Value3]
    enie:
        requires:
            - input
        page: enie.jsp
        parameters: []
    merge:
        requires:
            - input
            - joint_ere
            - enie
        page: merge.jsp
        parameters: []
    visualize:
        requires:
            - input
        page: visualize.jsp
        parameters: []
